# Netlify configuration for frontend build only
[build]
  base = "client"
  publish = "client/dist"
  command = "npm ci --legacy-peer-deps && npm run build"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "20"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
